local Mock = dofile("tests/mock.lua")
local count = 0
local function test(name, fn) fn(); count=count+1; print("PASS " .. name) end
test("unlock displays five synthetic rows matching live geometry", function()
    local m=Mock.New(); local a=m.Start()
    assert(not a.Preview.root.shown)
    a.View.SetUnlocked(true)
    assert(a.Preview.root.shown and #a.Preview.rows == 5)
    assert(a.Preview.root.mouse and a.Preview.root.level > a.View.root:GetFrameLevel())
    for i, row in ipairs(a.Preview.rows) do
        assert(row.health.width == a.View.rows[i].health.width)
        assert(row.health.height == a.View.rows[i].health.height)
        assert(row.power.height == a.View.rows[i].power.height)
        assert(row.name.text ~= "" and row.health.value > 0)
        assert(row.attributes.unit == nil and row.attributes.type1 == nil)
        assert(row.incoming.calculator == nil)
        assert(a.View.rows[i].alpha == 0)
    end
end)
test("live events never contaminate preview or persist sample data", function()
    local m=Mock.New(); local a=m.Start(); a.View.SetUnlocked(true)
    m.units.player.name="Actual Player"; m.units.player.health=10
    m.Event("GROUP_ROSTER_UPDATE"); m.Flush()
    assert(a.Preview.rows[1].name.text == "Priest" and a.Preview.rows[1].health.value == 100)
    assert(a.View.rows[1].health.value == 10)
    for key in pairs(a.db) do assert(key == "version" or key == "position" or key == "bindings" or key == "buffs") end
    assert(next(a.db.bindings) == nil)
    a.View.SetUnlocked(false)
    assert(not a.Preview.root.shown and a.View.rows[1].alpha == 1)
    assert(a.View.rows[1].name.text == "Actual")
end)
test("combat and drag completion exit preview without secure mutations", function()
    local m=Mock.New(); local a=m.Start(); a.View.SetUnlocked(true)
    m.combat=true; m.Event("PLAYER_REGEN_DISABLED"); m.Flush()
    assert(not a.Preview.root.shown and not a.View.unlocked)
    for _, row in ipairs(a.View.rows) do assert(row.alpha == 1) end
    a.View.SetUnlocked(true); assert(not a.Preview.root.shown)
    m.combat=false; m.Event("PLAYER_REGEN_ENABLED"); m.Flush()
    assert(not a.Preview.root.shown)
    a.View.SetUnlocked(true); a.View.handle.scripts.OnDragStart()
    a.View.handle.scripts.OnDragStop(); assert(not a.Preview.root.shown)
end)
test("preview holds full, animates and returns to full before repeating", function()
    local m=Mock.New(); local a=m.Start(); a.View.SetUnlocked(true)
    local p=a.Preview
    for _, row in ipairs(p.rows) do
        assert(row.health.value == 100 and row.power.value == 100)
        assert(row.incoming.bar.value == 0 and not row.drinkIcon.shown)
    end
    p.root.scripts.OnUpdate(p.root, 2.9); assert(p.rows[2].health.value == 100)
    p.root.scripts.OnUpdate(p.root, 1.1)
    assert(p.rows[2].health.value > 45 and p.rows[2].health.value < 100)
    p.root.scripts.OnUpdate(p.root, 2)
    assert(p.rows[2].health.value == 45 and p.rows[2].incoming.bar.value == 30)
    assert(p.rows[3].drinkIcon.shown)
    assert(p.rows[4].alpha == 0.45 and p.rows[4].status.text == "OUT OF RANGE")
    assert(p.rows[5].status.text == "OFFLINE" and p.rows[5].health.value == 0)
    assert(p.rows[5].power.value == 0 and p.rows[5].incoming.bar.value == 0)
    p.root.scripts.OnUpdate(p.root, 2)
    assert(p.rows[2].health.value > 45 and p.rows[2].health.value < 100)
    assert(p.rows[1].status.text == "DEAD" and p.rows[1].health.value == 0)
    assert(p.rows[4].alpha == 1 and p.rows[4].status.text == "")
    p.root.scripts.OnUpdate(p.root, 2.5)
    for _, row in ipairs(p.rows) do
        assert(row.health.value == 100 and row.power.value == 100)
        assert(row.incoming.bar.value == 0 and not row.drinkIcon.shown)
        assert(row.alpha == 1 and row.name.shown and row.status.text == "")
    end
    p.root.scripts.OnUpdate(p.root, 2); assert(p.rows[2].health.value == 100)
    a.View.SetUnlocked(false); assert(p.root.scripts.OnUpdate == nil)
    a.View.SetUnlocked(true); assert(p.elapsed == 0 and p.rows[2].health.value == 100)
    m.combat=true; m.Event("PLAYER_REGEN_DISABLED")
    assert(p.root.scripts.OnUpdate == nil and not p.root.shown)
end)
print(count .. " full-party preview scenarios passed")
